apiVersion: v1
data:
  api-timeout: "30000"
  client-url: https://faruq.xyz
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"api-timeout":"30000","client-url":"https://faruq.xyz"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"quickpad-config","namespace":"default"}}
  creationTimestamp: "2025-12-14T17:00:21Z"
  name: quickpad-config
  namespace: default
  resourceVersion: "1765731621016415001"
  uid: a83b65bd-a37f-48e6-8129-c1190e3e87bd
