apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: quickpad-backend-config
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600
  timeoutSec: 86400
  connectionDraining:
    drainingTimeoutSec: 60

